# Generated by Django 2.0.6 on 2018-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=250)),
                ('graph_description', models.CharField(max_length=1000)),
                ('graph_image', models.CharField(max_length=500)),
            ],
        ),
    ]
