# Generated by Django 2.0.6 on 2018-07-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=250)),
                ('site_location', models.CharField(max_length=1000)),
                ('site_description', models.CharField(max_length=500)),
                ('site_date_added', models.DateField()),
            ],
        ),
    ]
